### ISSUE TITLE
HCS12_Flashprogrammer

### ISSUE THREAD

**Issue by HondaRulez** [podonoghue/usbdm-eclipse-makefiles-build#5]
Hi,

The HCS12_Flashprogrammer failed to erase the device (S12GA240) when the code previously loaded with codeprotect.

In this case I use an another programmer to erase the device then I can program again.
(the error message is TCL script returned with error..)
(BTW how can I debug  what was happend ?,  where can I see the log meaasges of the TCL script )
I used on Linux and with the JS16 firmware.

When no codeprotection activated works fine at all.

**Comment by HondaRulez** [comment]
Anything on this ? Can I do something to solve this ? Kinetis based BDM may work ? (Currently I use HCS08 base BDM)

More info: this is not happened with G32, G48, G128 and VR devices.

**Comment by podonoghue** [comment]
Hi Ferenc,

I do not have access to a S12GA240 for testing and they don’t seem readily available from the distributors I use.
I have examined the reference manual that applies to the G and GA family and cannot find any reason why the GA240 should behave differently to the G128 device that I have for testing,
The only significant difference is the Flash size.

Your description of the problem is a bit unclear.  Please provide the following information:

·       When you say codeprotect are you referring to securing the device using an appropriate FSEC value or are you referring to protecting regions of Flash or EEPROM using the FPROT and FEPROT memory locations?

·       Exactly what USBDM programmer are you using USBDM-JS16-… etc?  You can run the firmware updater which will report the Hardware Version.

·       Are you using the GUI programs or command-line?

To obtain a debug log of the failure it is necessary to run the debug version of the software. Offhand I am unsure if that gets installed by default in Linux.  The executable is built “UsbdmFlashProgrammer-debug”.  Two log files are created. Usbdm.log and Flashprogrammer.log.  Again I’m unsure where these are created – either in the system temp location or in ~/.usbdm.  I don’t routinely use Linux.

I’ll have to install a virtual machine to do some more testing but it seems futile if the problem only occurs for GA240.

bye

**Comment by HondaRulez** [comment]
Hi,

thanks for your reply.

> 2018. jan. 10. dátummal, 23:00 időpontban podonoghue <notifications@github.com> írta:
> 
> Hi Ferenc, 
> 
> I do not have access to a S12GA240 for testing and they don’t seem readily available from the distributors I use. 
> I have examined the reference manual that applies to the G and GA family and cannot find any reason why the GA240 should behave differently to the G128 device that I have for testing, 
> The only significant difference is the Flash size. 
> 
> Your description of the problem is a bit unclear. Please provide the following information: 
> 
> · When you say codeprotect are you referring to securing the device using an appropriate FSEC value or are you referring to protecting regions of Flash or EEPROM using the FPROT and FEPROT memory locations? 
> 
yes, I referred to the securing. I’m put the FSEC value (with backdoor key) into the SREC file as follows: S113FF0043C5A76E5BF92D47FFFFFFFFCFFFFFBD82
then using -security:image -masserase optios for the cmd line tools.

I use same values for other G/VR series MCU and works fine.
Furthermore I use own bootloader, which is works on all devices, so no any issues with the flash erase commands.

> · Exactly what USBDM programmer are you using USBDM-JS16-… etc? You can run the firmware updater which will report the Hardware Version. 
I use USBDM-JS16 series.. (picture attached with version info)

> · Are you using the GUI programs or command-line? 
I using both of them, but mostly the Command line version. The error is exists on both version.

> To obtain a debug log of the failure it is necessary to run the debug version of the software. Offhand I am unsure if that gets installed by default in Linux. The executable is built “UsbdmFlashProgrammer-debug”. Two log files are created. Usbdm.log and Flashprogrammer.log. Again I’m unsure where these are created – either in the system temp location or in ~/.usbdm. I don’t routinely use Linux. 
> 
I compilled the tools to myself on MintMate 18.x. (x64), so i can run the debug versions.

> I’ll have to install a virtual machine to do some more testing but it seems futile if the problem only occurs for GA240. 
> 
> bye 

Just for a starting point to find the problem.

I did not see how the firmware works in the USBDM but the only differences between the working and not working devices is that the global adresse with the NON working device (GA240) is started with 0x004000.
so the most UPPER byte is 0x00 which is same with the EEPROM “page” when we doing FLASH erase command. 

The logs for a “MassErase” command (initiated from the GUI) are attached.
(files was found in the ~/.usbdm/ ditrectory)

Bye

[result.log](https://github.com/podonoghue/usbdm-eclipse-makefiles-build/files/1622199/result.log)
[usbdm.log](https://github.com/podonoghue/usbdm-eclipse-makefiles-build/files/1622200/usbdm.log)
![usbdm1](https://user-images.githubusercontent.com/12637942/34821564-7d255892-f6c4-11e7-8b51-f38bb48ea60f.png)
![usbdm2](https://user-images.githubusercontent.com/12637942/34821566-7d81a57a-f6c4-11e7-9a49-f4508cf2f20f.png)
![usbdm3](https://user-images.githubusercontent.com/12637942/34821568-7dbed9a4-f6c4-11e7-9e14-66be2bd577d4.png)
![usbdm4](https://user-images.githubusercontent.com/12637942/34821569-7e48468a-f6c4-11e7-880b-cc7f751038bb.png)
![usbdm5](https://user-images.githubusercontent.com/12637942/34821570-7e84f134-f6c4-11e7-887d-0404e5293300.png)
